# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Caller
version:      2.02
version_from: lib/Devel/Caller.pm
installdirs:  site
requires:
    PadWalker:                     0.08
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
